### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by boromyr** [BsCmOD/Marlin-2.0.5-for-SKR1.4-for-Alfawise-U30Pro-Longer-LK4PRo#1]
E' compatibile con lo screen della U30 Pro o bisogna sostituirlo?

**Comment by BsCmOD** [comment]
> E' compatibile con lo screen della U30 Pro o bisogna sostituirlo?

No, per forza di cose bisogna sostituirlo anche perché in quel modo con un tft35 riusciresti ad sfruttare tutte le funzioni di marlin

**Comment by boromyr** [comment]
Ok grazie, nel frattempo ho già installato la tua nuova versione del touchscreen con le nuove funzioni ;)

**Comment by BsCmOD** [comment]
> Ok grazie, nel frattempo ho già installato la tua nuova versione del touchscreen con le nuove funzioni ;)

Perfetto!
